package types

const (
	ContentType             = "Content-Type"
	ContentLength           = "Content-Length"
	ContentEncoding         = "Content-Encoding"
	CacheControl            = "Cache-Control"
	LastModified            = "Last-Modified"
	ETag                    = "ETag"
	IfNoneMatch             = "If-None-Match"
	IfModifiedSince         = "If-Modified-Since"
	Expires                 = "Expires"
	Age                     = "Age"
	Vary                    = "Vary"
	Date                    = "Date"
	StrictTransportSecurity = "Strict-Transport-Security"
	Authorization           = "Authorization"
	SetCookie               = "Set-Cookie"
	AcceptEncoding          = "Accept-Encoding"
	AcceptRanges            = "Accept-Ranges"
	TrueClientIP            = "True-Client-IP"
	XRealIP                 = "X-Real-IP"
	XForwardedFor           = "X-Forwarded-For"
	XCache                  = "X-Cache"
	XTraceID                = "X-Trace-Id"
)
